api/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token

from api import views as api_view

router = routers.DefaultRouter()
router.register(r'farmers', api_view.FarmerViewSet)
router.register(r'farm', api_view.FarmViewSet)
router.register(r'farm-field', api_view.FarmFieldViewSet)

app_name = 'api'
urlpatterns = [
    url(r'^', include(router.urls)),
    # url(r'^', include(router.urls, namespace='api')),
    url(r'^token/$', obtain_auth_token),
]

farmer/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^api/', include("api.urls")),
    url(r'^api-auth/', include(
        'rest_framework.urls', namespace='rest_framework')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include("website.urls")),
]

website/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.views.generic import RedirectView

from website import views as website_view

app_name = 'website'
urlpatterns = [
    url(r'^index/$', website_view.index, name="index"),
    url(r'^$',
        RedirectView.as_view(url="/index/", permanent=False),
        name="init"),
    url(r'^farm/$', website_view.farm, name="farm"),
    url(r'^farm-field/$', website_view.farm_field, name="farm_field"),

]

urlpatterns += [
    url('^', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bio_data/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


# Create your models here.
class FarmerBioData(models.Model):
    name = models.CharField(max_length=75)
    contact_no = models.CharField(max_length=10, blank=True, null=True)
    address = models.TextField(max_length=500, blank=True, null=True)
    pin = models.PositiveIntegerField(blank=True, null=True)
    is_active = models.BooleanField(default=True)
    created_on = models.DateTimeField(editable=False, auto_now_add=True)
    # Only on creation
    update_on = models.DateTimeField(editable=False, auto_now=True)

    # On every save

    def __unicode__(self):
        return self.name

farm_field/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.db import models

# Create your models here.
from bio_data.models import FarmerBioData


class Farm(models.Model):
    farmer = models.ForeignKey(
        FarmerBioData, related_name=u"farm", on_delete=models.CASCADE)
    name = models.CharField(max_length=75)
    details = models.CharField(max_length=75)
    is_active = models.BooleanField(default=True)
    created_on = models.DateTimeField(editable=False, auto_now_add=True)
    # Only on creation
    update_on = models.DateTimeField(editable=False, auto_now=True)
    # On every save

    def __unicode__(self):
        return self.name


class FarmField(models.Model):
    farm = models.ForeignKey(Farm, related_name=u"farmfield")
    name = models.CharField(max_length=75)
    season = models.CharField(max_length=2, choices=settings.SEASON)
    crop_type = models.CharField(max_length=2, choices=settings.CROP_TYPE)
    is_active = models.BooleanField(default=True)
    field_from = models.DateField()
    field_to = models.DateField()
    # point 1:point2:point3:point 4
    # 1.234568,2.34343:13.234324,15.23234234:..etc
    land_coordinates = models.CharField(
        max_length=150, default=None, null=True)
    created_on = models.DateTimeField(editable=False, auto_now_add=True)
    # Only on creation
    update_on = models.DateTimeField(editable=False, auto_now=True)
    # On every save

website/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

api/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

# Create your views here.
from rest_framework import viewsets, renderers
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated

from api.serializers import (
    FarmerBioDataSerializer, FarmSerializer, FarmFieldSerializer)
from bio_data.models import FarmerBioData
from farm_field.models import Farm, FarmField


class FarmerViewSet(viewsets.ModelViewSet):
    # permission_classes = (IsAuthenticated,)
    # authentication_classes = (TokenAuthentication,)
    # renderer_classes = (renderers.JSONRenderer,)
    queryset = FarmerBioData.objects.all().order_by('-update_on')
    serializer_class = FarmerBioDataSerializer


class FarmViewSet(viewsets.ModelViewSet):
    # permission_classes = (IsAuthenticated,)
    # authentication_classes = (TokenAuthentication,)
    # renderer_classes = (renderers.JSONRenderer,)
    queryset = Farm.objects.all().order_by('-update_on')
    serializer_class = FarmSerializer


class FarmFieldViewSet(viewsets.ModelViewSet):
    # permission_classes = (IsAuthenticated,)
    # authentication_classes = (TokenAuthentication,)
    # renderer_classes = (renderers.JSONRenderer,)
    queryset = FarmField.objects.all().order_by('-update_on')
    serializer_class = FarmFieldSerializer

bio_data/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

website/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.shortcuts import render


# Create your views here.
from bio_data.models import FarmerBioData
from farm_field.models import Farm


def index(request):
    return render(request, "index.html", locals(), content_type="text/html",
                  status=200)

def farm(request):
    farmers = FarmerBioData.objects.all()
    return render(request, "farm.html", locals(), content_type="text/html",
                  status=200)


def farm_field(request):
    farms = Farm.objects.all()
    seasons = settings.SEASON_DICT
    crop_types = settings.CROP_TYPE_DICT

    return render(request, "farm-field.html", locals(), content_type="text/html",
                  status=200)

farmer/templates/farm-field.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.2.0/dist/leaflet.css"
   integrity="sha512-M2wvCLH6DSRazYeZRIm1JnYyh22purTM+FDB5CsyxtQJYeKq83arPe5wgbNmcFXGqiSH2XR8dT/fJISVA1r/zQ=="
   crossorigin=""/>
    <style>
        #mapid { height: 350px; }
    </style>
    <script src='https://api.mapbox.com/mapbox-gl-js/v0.40.0/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v0.40.0/mapbox-gl.css' rel='stylesheet' />
    <link rel="stylesheet" href="/static/js/leaf/leaflet.draw.css"/>

</head>
<body>
<h1>farm field</h1>
<a href="#" class="cls_open_add_farm_field">Add farm field</a>
<div style="display:none;" id="id_html_add_farm_field">
    <form method="post" action="/api/farm-field/" onsubmit="return false;" id="id_frm_add_farm_field">
        {%csrf_token%}
        <select name="farm_id" required>
            <option>- select farm</option>
        {% for farm in farms %}
            <option value="{{farm.id}}">{{farm.name}}</option>
        {% endfor%}
        </select>
        <input type="text" name="name" placeholder="Farm Name" maxlength="50" required />

        <select name="season" required>
            <option>- select season</option>
        {% for key, value in seasons.items %}
            <option value="{{key}}">{{value}}</option>
        {% endfor%}
        </select>

        <select name="crop_type" required>
            <option>- select crop</option>
        {% for key, value in crop_types.items %}
            <option value="{{key}}">{{value}}</option>
        {% endfor%}
        </select>

        <input type="text" name="field_from" placeholder="Crop Start Date" maxlength="10" required />
        <input type="text" name="field_to" placeholder="Crop End Date" maxlength="10" required />
        <div id="mapid"></div>
        <input type="hidden" name="land_coordinates" id="id_land_coordinates" value="" />

        <button type="submit">Save</button>
    </form>
</div>

<h3>List</h3>
<table id="farm_field" class="display" width="100%" cellspacing="0" border="1">
    <thead>
    <tr>
        <th>Farm Field</th>
        <th>Farm Name</th>
        <th>Crop</th>
        <th>Season</th>
        <th>Start date</th>
        <th>End Date</th>
        <th>Delete</th>
    </tr>
    </thead>
    <tfoot>
    <tr>
        <th>Farm Field</th>
        <th>Farm Name</th>
        <th>Crop</th>
        <th>Season</th>
        <th>Start date</th>
        <th>End Date</th>
        <th>Delete</th>
    </tr>
    </tfoot>
</table>

<script src="//code.jquery.com/jquery-1.12.4.js"></script>
<script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<!--https://jsfiddle.net/user2314737/324h2d9q/-->
<script src="https://unpkg.com/leaflet@1.2.0/dist/leaflet.js"
   integrity="sha512-lInM/apFSqyy1o6s89K4iQUKg6ppXEgsVxT35HbzUupEVRh2Eu9Wdl4tHj7dZO0s1uvplcYGmt3498TtHq+log=="
   crossorigin=""></script>
<script src="/static/js/leaf/Leaflet.draw.js"></script>
<script src="/static/js/leaf/Leaflet.Draw.Event.js"></script>

<script src="/static/js/leaf/Toolbar.js"></script>
<script src="/static/js/leaf/Tooltip.js"></script>

    <script src="/static/js/leaf/GeometryUtil.js"></script>

    <script src="/static/js/leaf/LatLngUtil.js"></script>
    <script src="/static/js/leaf/LineUtil.Intersect.js"></script>
    <script src="/static/js/leaf/Polygon.Intersect.js"></script>
    <script src="/static/js/leaf/Polyline.Intersect.js"></script>
    <script src="/static/js/leaf/TouchEvents.js"></script>

    <script src="/static/js/leaf/DrawToolbar.js"></script>
    <script src="/static/js/leaf/dt_handler/Draw.Feature.js"></script>
    <script src="/static/js/leaf/dt_handler/Draw.SimpleShape.js"></script>
    <script src="/static/js/leaf/dt_handler/Draw.Polyline.js"></script>
    <script src="/static/js/leaf/dt_handler/Draw.Marker.js"></script>
    <script src="/static/js/leaf/dt_handler/Draw.Circle.js"></script>
    <script src="/static/js/leaf/dt_handler/Draw.CircleMarker.js"></script>
    <script src="/static/js/leaf/dt_handler/Draw.Polygon.js"></script>
    <script src="/static/js/leaf/dt_handler/Draw.Rectangle.js"></script>


<script src="/static/js/leaf/Control.Draw.js"></script>
<script>window.leaf_map=true;</script>

<script src="/static/js/client.js"></script>
<!--<div id='map' style='width: 400px; height: 300px;'></div>-->
<!--<script>-->
  <!--mapboxgl.accessToken = 'pk.eyJ1IjoiamtuYXJlc2giLCJhIjoiY2o4YmFmaWlpMGMwcDJxcDYxaDgxaXIwciJ9.qBkVUuA-N3PkyMBgPddVUA';-->
  <!--var map = new mapboxgl.Map({-->
    <!--container: 'map',-->
    <!--style: 'mapbox://styles/mapbox/streets-v10'-->
  <!--});-->
<!--</script>-->
<!--// https://leaflet.github.io/Leaflet.draw/docs/examples-0.7.x/full.html-->
<!--// https://github.com/Leaflet-->

</body>
</html>

farmer/templates/farm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Farm</h1>
<a href="#" class="cls_add_farm">Add farm</a>
<div style="display:none" id="id_frm_html">
    <form method="post" action="/api/farm/" onsubmit="return false;" class="cls_frm_save_farm">
        {% csrf_token%}
        <select name="farmer_id">
            <option>-Select Farmer</option>
            {% for farmer in farmers %}
            <option value="{{farmer.id}}">Farmer {{farmer.name}}</option>
            {% endfor %}
        </select>
        <input type="text" name="name" placeholder="Farm Name" maxlength="50" required />
        <input type="text" name="details" placeholder="Farm details" maxlength="50" required />
        <button type="submit">Save</button>
    </form>
</div>
<h4>List</h4>
<table id="farm" class="display" width="100%" cellspacing="0" border="1">
    <thead>
    <tr>
        <th>Farm Name</th>
        <th>Details</th>
        <th>Farmer</th>
        <th>Delete</th>
    </tr>
    </thead>
    <tfoot>
    <tr>
        <th>Farm Name</th>
        <th>Details</th>
        <th>Farmer</th>
        <th>Delete</th>
    </tr>
    </tfoot>
</table>
<script src="//code.jquery.com/jquery-1.12.4.js"></script>
<!--<script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script>-->
<script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script src="/static/js/client.js"></script>

</body>
</html>

farmer/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Farmer</title>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <style>
    label, input { display:block; }
    input.text { margin-bottom:12px; width:95%; padding: .4em; }
    fieldset { padding:0; border:0; margin-top:25px; }
    h1 { font-size: 1.2em; margin: .6em 0; }
    div#users-contain { width: 350px; margin: 20px 0; }
    div#users-contain table { margin: 1em 0; border-collapse: collapse; width: 100%; }
    div#users-contain table td, div#users-contain table th { border: 1px solid #eee; padding: .6em 10px; text-align: left; }
    .ui-dialog .ui-state-error { padding: .3em; }
    .validateTips { border: 1px solid transparent; padding: 0.3em; }
    </style>
</head>
<body>
<h1>Farmers</h1>
<a href="#" class="cls_add_farmer">Add Farmer</a>
<table id="farmers" class="display" width="100%" cellspacing="0" border="1">
    <thead>
    <tr>
        <th>Name</th>
        <th>Phone</th>
        <th>Pin</th>
        <th>Address</th>
        <th>Delete</th>
    </tr>
    </thead>
    <tfoot>
    <tr>
        <th>Name</th>
        <th>Phone</th>
        <th>Pin</th>
        <th>Address</th>
        <th>Delete</th>
    </tr>
    </tfoot>
</table>

<div id="farmer-dialog-form" title="Create new user">
  <p class="validateTips">All form fields are required.</p>
  <form method="post" action="/api/farmers/" class="cls_frm_add_farmer">
      {% csrf_token%}
    <fieldset>
      <label for="name">Name</label>
      <input type="text" name="name" id="name" placeholder="Enter Name"
             class="text ui-widget-content ui-corner-all" />
      <label for="email">Phone</label>
      <input type="text" name="contact_no" id="email" placeholder="mobile no"
             class="text ui-widget-content ui-corner-all">
      <label for="password">Pin</label>
      <input type="text" name="pin" id="password" placeholder="Pin"
             class="text ui-widget-content ui-corner-all">
        <label for="address">address</label>
      <input type="text" name="address" id="address" placeholder="Address"
             class="text ui-widget-content ui-corner-all">

      <!-- Allow form submission with keyboard without duplicating the dialog button -->
      <input type="submit" tabindex="-1"
             style="position:absolute; top:-1000px" value="Save"/>
    </fieldset>
  </form>
</div>

<script src="//code.jquery.com/jquery-1.12.4.js"></script>
<script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>

<script src="/static/js/client.js"></script>
</body>
</html>